### PR TITLE
Add docker role to setup_dev_environment.yml

### LINKED ISSUE #238: add  installing docker and docker-compose to ansible roles
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when run `sh setup.sh` without installing docker.

**Describe the solution you'd like**
add  installing docker and docker-compose to ansible roles

### PR DESCRIPTION
**Pull request by HansRobo**
This PR will resolve #238 and #245

### CODE REVIEW

**Comment by swiftfile** [comment]
@HansRobo 
Thanks for improving on my behalf!
By the way, Is this PR still a work in progress?
Of course, This PR will enhance this repo( #238 ). But, I think this PR does not resolve #245.

**Comment by HansRobo** [comment]
@swiftfile 
Actually, the docker role is including `sshpass` installation.

**Comment by HansRobo** [comment]
https://github.com/OUXT-Polaris/ouxt_automation/blob/master/ansible/roles/docker/tasks/main.yml#L19

**Comment by swiftfile** [comment]
I wasn't careful enough...
@HansRobo Thanks for the explanation!
LGTM!

**Pull request closed without merging**
